version: "3"

services:
  frontend:
    build:
      context: ./docker/frontend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
    working_dir: /app
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - TZ='Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  nginx:
    image: nginx:latest
    depends_on:
      - frontend
      - db
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
