version: "3.8"

services:
  app:
    build:
      context: ./docker/app
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
    working_dir: /app
  nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:8.0
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ='Asia/Tokyo'
    ports:
      - 3306:3306

volumes:
  node_modules:
