version: "3"

services:
  frontend:
    build:
      context: ./frontend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: sleep infinity
    ports:
      - 5173:5173
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - TZ='Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
  nginx:
    image: nginx:latest
    depends_on:
      - frontend
      - db
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html

volumes:
  node_modules:
